import type { Metadata } from "next";
import localFont from "next/font/local";
import AuthenticationProvider from "./core/Context/Authentication.context";
import "./globals.css";
import "./styles/element.global.scss";
import "./styles/theme.global.css";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

import { Inter } from "next/font/google";
import { ApplicationErrorProvider } from "./core/Context/ApplicationError";
import ThemeProvider from "./core/Context/Theme";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });
// If loading a variable font, you don't need to specify the font weight

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${inter.className}`}
      >
        <ApplicationErrorProvider>
          <ThemeProvider>
            <div className="absolute pointer-events-none top-0 w-full h-[50rem]">
              <Image
                src={
                  "https://tailwindcss.com/_next/static/media/docs-dark@30.1a9f8cbf.avif"
                }
                width={100}
                height={100}
                alt="bg"
                className="w-full h-full"
              />
            </div>
            <AuthenticationProvider>{children}</AuthenticationProvider>
          </ThemeProvider>
        </ApplicationErrorProvider>
      </body>
    </html>
  );
}
