import type { Metadata } from "next";
import "./globals.css";

import { Poppins } from "next/font/google";
import TanstackQueryProvider from "./context/TanstackQuery/TanstackQuery.context";
import ReduxProvider from "@/lib/Redux/Provider";
// If loading a variable font, you don't need to specify the font weight

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`antialiased `}>
        <ReduxProvider>
          <TanstackQueryProvider>{children}</TanstackQueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
