const ALERT_ERROR_TITLE_DEFAULT = 'Lỗi không xác định'
const ALERT_ERROR_TITLE_AUTH = 'Lỗi xác thực'
const ALERT_ERROR_TITLE_API = 'Lỗi gọi API'
const ALERT_ERROR_TITLE_APPLICATION = 'Lỗi phần mền nội bộ'

export { ALERT_ERROR_TITLE_API, ALERT_ERROR_TITLE_APPLICATION, ALERT_ERROR_TITLE_AUTH, ALERT_ERROR_TITLE_DEFAULT }
